name: SE333_CI
on:
  push:
    branches:
      - main

jobs:
  SE333_CI_JOB:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4

      - name: setupJava
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          architecture: x64

      - name: Install Linter
        run: mvn -B -q -DskipTests clean verify || true

      - name: Run Checkstyle
        run: mvn -B -DskipTests=true validate

      - name: Upload Checkstyle Result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: |
            target/checkstyle.xml
            **/target/checkstyle.xml

      - name: Run Maven Test
        run: mvn -B test

      - name: Jacoco Report
        run: mvn -B jacoco:report

      - name: JaCoCo Upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: |
            target/site/jacoco/*